# Generated by Django 4.2 on 2023-05-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="mobile",
            field=models.TextField(default="", max_length=10),
        ),
    ]
