# Generated by Django 4.2 on 2023-04-25 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "booked_from",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Check In Date"
                    ),
                ),
                (
                    "booked_till",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Check Out Date"
                    ),
                ),
                (
                    "reservation_status",
                    models.TextField(
                        choices=[
                            ("Check In", "Checked In"),
                            ("Check Out", "Checked Out"),
                            ("Hold", "On Hold"),
                        ],
                        default="On Hold",
                        max_length=40,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rooms",
            fields=[
                (
                    "room_no",
                    models.CharField(
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Room No",
                    ),
                ),
                (
                    "room_type",
                    models.TextField(
                        choices=[
                            ("Premium", "Premium"),
                            ("Classic", "Classic"),
                            ("Cottage", "Cottage"),
                        ],
                        default="Classic",
                        max_length=30,
                    ),
                ),
                ("room_price", models.IntegerField(default=0)),
                ("room_available", models.BooleanField(default=True)),
            ],
        ),
    ]
