# Generated by Django 4.2 on 2023-04-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="payment_id",
            field=models.CharField(
                default="", max_length=36, verbose_name="Payment ID"
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="provider_order_id",
            field=models.CharField(default="", max_length=40, verbose_name="Order ID"),
        ),
        migrations.AddField(
            model_name="reservation",
            name="signature_id",
            field=models.CharField(
                default="", max_length=128, verbose_name="Signature ID"
            ),
        ),
    ]
