# Generated by Django 4.2 on 2023-04-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0002_reservation_payment_id_reservation_provider_order_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="reservation", name="reservation_status",),
        migrations.AddField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                default="Pending", max_length=254, verbose_name="Payment Status"
            ),
        ),
    ]
