# Generated by Django 4.2 on 2023-04-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0003_remove_reservation_reservation_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="reservation", name="status",),
        migrations.AddField(
            model_name="reservation",
            name="payment_status",
            field=models.CharField(
                default="Pending", max_length=254, verbose_name="Payment Status"
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="reservation_status",
            field=models.TextField(
                choices=[
                    ("Check In", "Checked In"),
                    ("Check Out", "Checked Out"),
                    ("Hold", "On Hold"),
                ],
                default="On Hold",
                max_length=40,
            ),
        ),
    ]
