# Generated by Django 4.2 on 2023-05-01 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0005_alter_reservation_reservation_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="booked_room",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="rooms.rooms",
            ),
        ),
    ]
