# Generated by Django 4.2 on 2023-05-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0006_alter_reservation_booked_room"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="reservation_amount",
            field=models.FloatField(default=0, verbose_name="Amount Paid"),
        ),
    ]
